dose_analytics:
  target: prod
  outputs:
    prod:
      type: postgres
      host: aws-1-us-east-2.pooler.supabase.com
      port: 5432
      user: "postgres.foxgsdzhvcmcydujjoit"
      password: "{{ env_var('SUPABASE_PASSWORD') }}"
      dbname: postgres
      schema: public
      threads: 4
